---
title: "Lab 3 Report"
author: "Phillip Hagen"
date: "`r format(Sys.Date())`"
output: github_document
---

Instructions for this lab report can be found on [Your assignment section of Lab Assignment 3 Introduction to ggplot2](https://biol275-msum.github.io/introduction-to-ggplot2.html#your-assignment) on the lab website.

## Fireflies

> A. Insert an R code chunk and create a graph depicting the frequency distribution of the 35 mass measurements. It should have legible text and appropriate axis labels.

ggplot(data = fireflies_data) +
  geom_histogram(mapping = aes(x = spermatophoreMass), binwidth = .005,
                 
                fill = "#C5351B", color = "black") +
  labs(x = "spermatophoreMass", y = "Frequency (number of fireflies)") +
  
  theme_classic() +
  theme(
    axis.title = element_text(face = "bold"),
    axis.text = element_text(color = "black", size = rel(1))
  )

> B. What type of graph did you choose in part (A)? Why?

I chose a histogram. The reason I chose this type of graph is because it groups the numbers in to ranges. 

> C. Describe the shape of the frequency distribution. What are its main features?

The shape is unimodal skewing right. There is a major clump at the beginning between 0 and 0.10 and a small clump at the end.

> D. What term would be used to describe the largest measurement in the frequency distribution? You can refer to the lecture slides, your notes, or the textbook.

Median 

## Bird orders

I read the data using the code provided by the instructor. The dataset is from the auk package and was originally named ebird_taxonomy. I converted it to a tibble, removed non-species taxa, and named the new dataset birds.

```
library(auk)                          # load the auk package
birds <- ebird_taxonomy %>%           # start with the ebird_taxonomy data
  as_tibble() %>%                     # tibbles print better in the console
  filter(category == "species")       # remove non-species taxa
```

> E. How many bird species are in the new birds dataset? How did you find out?

There are 16,513 bird species in the dataset. When I created the data set it showed 16,513 rows. Meaning that there are 16,513 birds species. 

> H. How many orders are there? You can get this right by counting on the graph, but you will only get full points if you use some code to figure it out.

There are 41 orders. When I examined the data I had a graph that showed 41 lines when I ws looking at the orders.   

> F. Insert an R code chunk and create a graph depicting the distribution of orders in the birds dataset. Sort the orders with the most frequent on the left. It should have legible text and appropriate axis labels.

ggplot(data = ebird_taxonomy) +
  geom_bar(mapping = aes(x = fct_infreq(order)), fill = "#C5351B", 
           width = .8) +
  labs(x = "Order", y = "Frequency (log number of bird species)", 
       title = "Number of bird species in each order") +
  scale_y_log10() +
  theme_classic(base_size = 12) +
  theme(
    axis.title = element_text(face = "bold"),
    axis.text = element_text(color = "black", size = rel(.8)),
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.ticks.x = element_blank()
  )

> G. What kind of graph did you create? Why?

I created a bar graph. I did this because we were creating graphs of categorical data, which is easiest depicted on a bar graph. 

## Links to peer review

I reviewed Kennan's lab report at this URL: \_\_\_

Kennan reviewed my lab report at this URL: \_\_\_

## Session Info

Here is my session information:

```{r}
sessioninfo::session_info()
```
